apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    server {
      listen 80;

      root /user/share/nginx/html;
      index index.html index.htm;

      #server_name your_domain www.your_domain;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /graphql {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://gateway-svc:3500/graphql;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    } 
