apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-service-pvc
  labels:
    app: chat-service-db
spec:
  #storageClassName: db-storage-class
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
