apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: mariolanzaldo/chat-service
        #command: ["tail", "-f", "/dev/null"]
        env:
          - name: MONGO_URL
            value: mongodb://chat-db-svc:27017/
          - name: PORT
            value: "4500"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        #ports:
        #- containerPort: <Port>
