apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: nginx-configmap-volume
          configMap:
            name: nginx-configmap
      containers:
      - name: frontend
        image: mariolanzaldo/frontend
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: nginx-configmap-volume
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        #ports:
        #- containerPort: <Port>
