apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: mariolanzaldo/api-gateway
        env:
        - name: PORT
          value: "3500"
        - name: API_USERS
          value: http://users-service-svc:5500
        - name: API_AUTH
          value: http://auth-service-svc:5000
        - name: API_CHAT
          value: http://chat-service-svc:4500
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        #ports:
        #- containerPort: <Port>
