apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db-deployment
  labels:
    app: auth-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-db
  template:
    metadata:
      labels:
        app: auth-service-db
    spec:
      containers:
      - name: mongo
        image: mongo
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
