apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
   #type: NodePort
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
